### ISSUE TITLE
Use correct category value in library properties

### ISSUE THREAD

**Issue by gioblu** [gioblu/Agenda#2]
As title says fill category with a correct value!

**Comment by Iucky** [comment]
Look at: https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification

> library.properties file format
> 
> The library.properties file is a key=value properties list. Every field in this file is UTF-8 encoded. The available fields are:
> ...
> category - if present, one of these: "Display", "Communication", "Signal Input/Output", "Sensors", "Device Control", "Timing", "Data Storage", "Data Processing", "Other"
> ...

Sounds like: you can not define your own category.

**Comment by gioblu** [comment]
Added "Timing" as category.
Thank you :+1:
